sudo: false
language: cpp
compiler:
  - gcc
  - clang
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
    - libgtest-dev
notifications:
  email: false
script:
  - pushd $TRAVIS_BUILD_DIR
  - pwd
  - wget http://tetgen.org/files/tetgen1.4.3.tar.gz
  - tar xzvf ./tetgen1.4.3.tar.gz
  - cd tetgen1.4.3
  - make tetlib
  - popd
  - mkdir build
  - cd build
  - pwd
  - wget http://www.sci.utah.edu/devbuilds/seg3d/tetgen_cmake.tgz
  - tar xzvf ./tetgen_cmake.tgz
  - cmake -DBUILD_TESTING:BOOL=OFF -DTravisCI_BUILD:BOOL=ON -DTetgen_DIR=$TRAVIS_BUILD_DIR/tetgen1.4.3 .. && make
#  - cmake -DBUILD_TESTING:BOOL=OFF .. && make
