sudo: false
language: cpp
notifications:
  email: false
compiler:
  - gcc
  - clang
#before_cache:
cache:
  directories:
    - $HOME/deps
before_install:
  # set up dependency cache
  - if [ ! -d $HOME/deps ]; then mkdir $HOME/deps; fi
  - cd $HOME/deps
  - if [ ! -f "tetgen1.4.3.tar.gz" ]; then wget http://tetgen.org/files/tetgen1.4.3.tar.gz; fi
  - if [ ! -f "tetgen_cmake.tgz" ]; then wget http://www.sci.utah.edu/devbuilds/seg3d/tetgen_cmake.tgz; fi
  - if [ ! -f "release-1.7.0.tar.gz" ]; then wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz; fi
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
#before_script:
script:
  - mkdir build
  - cd build
  - tar xzf $HOME/deps/tetgen1.4.3.tar.gz
  - pushd tetgen1.4.3
  - make tetlib
  - tar xzf $HOME/deps/tetgen_cmake.tgz
  - popd
  - tar xzvf $HOME/deps/release-1.7.0.tar.gz
  - pushd googletest-release-1.7.0
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  - popd
  - cmake -DBUILD_TESTING:BOOL=ON -DTravisCI_BUILD:BOOL=ON -DGTEST_INCLUDE_DIR:PATH=`pwd`/googletest-release-1.7.0/include -DGTEST_LIBRARY:FILEPATH=`pwd`/googletest-release-1.7.0/build/libgtest.a -DGTEST_MAIN_LIBRARY:FILEPATH=`pwd`/googletest-release-1.7.0/build/libgtest_main.a -DTetgen_DIR=`pwd`/tetgen1.4.3 ..
  - make -j4
#after_failure:
after_success:
  - ./ImplicitFunction_Tests
#after_script:
